POST http://localhost:3000/api/users
Content-Type: application/json

{
    "fullName": "Abiodun Shittu",
	"email": "abiodunshittu@gmail.com",
	"password": "abiodunshittu"
}

###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
	"email": "abiodunshittu@gmail.com",
	"password": "abiodunshittu"
}